version: 0.2

phases:
  install:
    commands:
      # Terraformのバージョンを指定
      - TERRAFORM_VERSION="1.5.7"
      # Terraformのzipファイルをダウンロード
      - wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      # zipファイルを解凍
      - unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      # 実行ファイルをパスの通ったディレクトリに移動
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init
  build:
    commands:
      - echo "Terraform plan and apply..."
      - terraform plan
      - terraform apply -auto-approve